# Generated by Django 3.0.7 on 2021-05-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_users_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=50)),
                ('ngo_name', models.CharField(max_length=50)),
                ('amount_req', models.PositiveIntegerField()),
                ('amount_donated', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('razorpay_id', models.CharField(max_length=50, unique=True)),
                ('cause_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.Causes')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.Users')),
            ],
        ),
    ]
