# Generated by Django 3.0.7 on 2021-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_causes_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='amount_donated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
