# Generated by Django 3.0.7 on 2021-05-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20210501_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='cause_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Causes'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Users'),
        ),
    ]
