# Generated by Django 3.0.7 on 2021-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20210501_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
