# Generated by Django 3.1.7 on 2021-05-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_donations_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
