# Generated by Django 3.1.7 on 2021-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_donations_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='email',
        ),
    ]
