# Generated by Django 3.0.7 on 2021-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_causes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='image',
            field=models.ImageField(default='images/index/img-4.jpg', upload_to='cause_images/'),
        ),
    ]
