# Generated by Django 3.0.7 on 2021-05-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_auto_20210506_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='image',
        ),
    ]
