# Generated by Django 3.0.7 on 2021-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_remove_causes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='image',
            field=models.URLField(default='images/index/img-4.jpg'),
        ),
    ]
