# Generated by Django 3.0.7 on 2021-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_causes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='image',
            field=models.URLField(default='static/images/index/img-4.jpg'),
        ),
    ]
