# Generated by Django 3.0.7 on 2021-05-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_auto_20210506_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='cause_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donor.Causes'),
        ),
    ]
