# Generated by Django 3.0.7 on 2021-05-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_auto_20210507_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='cause_name',
            field=models.CharField(default='deflt', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donations',
            name='cause_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Causes'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donor.Users'),
        ),
    ]
